### ISSUE TITLE
column "id" referenced in foreign key constraint does not exist

### ISSUE THREAD

**Issue by Hanko2024** [MichaelDBA/pg_get_tabledef#12]
CREATE SCHEMA a;
create table a.test_parent_a (i serial primary key);

CREATE TABLE a.test_child_b( 
CONSTRAINT test_child_b_id_fkey FOREIGN KEY (id) REFERENCES a.test_parent_a(i)
) INHERITS (a.test_parent_a) TABLESPACE pg_default;
CREATE UNIQUE INDEX test_child_b_pkey ON a.test_child_b USING btree (id) TABLESPACE pg_default;

err
dts1=> CREATE TABLE a.test_child_b( 
dts1(> CONSTRAINT test_child_b_id_fkey FOREIGN KEY (id) REFERENCES a.test_parent_a(i)
dts1(> ) INHERITS (a.test_parent_a) TABLESPACE pg_default;
ERROR:  column "id" referenced in foreign key constraint does not exist

**Comment by Hanko2024** [comment]
PostgreSQL 11.12 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

**Comment by MichaelDBA** [comment]
@liuhangyu That is just plain wrong SQL.  What does that have to do with pg_get_tabledef()?

**Comment by MichaelDBA** [comment]
@liuhangyu Gonna close this if you do not respond.

**Comment by MichaelDBA** [comment]
Closing this issue since it is not an issue with pg_get_tabledef since it is not involved in the error generated above.
