### ISSUE TITLE
Columns with a custom type (citext) referencing the wrong schema

### ISSUE THREAD

**Issue by alaister** [MichaelDBA/pg_get_tabledef#15]
Hey Michael,
Thanks for fixing the last bug. Found another small one:

With the following SQL:
```sql
create extension citext schema extensions;

create table public.example (
  id uuid not null primary key default gen_random_uuid(),
  name extensions.citext not null
);
```
The definition is showing as:
```sql
create table public.example (
    id uuid not null default gen_random_uuid (),
    name public.citext not null,
    constraint example_pk primary key (id)
  ) tablespace pg_default;
```

As you can see, the definition should show the type of `name` as `extensions.citext`, but it's showing as `public.citext`.

**Comment by MichaelDBA** [comment]
@alaister Finally got around to fixing this.  Please test and validate.  Thanks.

**Comment by MichaelDBA** [comment]
Curious, exactly how does pg_get_tabledef fit into supabase?  clone table?

**Comment by alaister** [comment]
We're using it in the table definition tab inside our table editor:
<img width="777" alt="Screenshot 2023-08-04 at 7 20 20 pm" src="https://github.com/MichaelDBA/pg_get_tabledef/assets/10985857/ec6f24ff-aee0-4631-9b40-35ed8983b91f">

Originally this feature was only for views, but we then extended it to tables with the help of this awesome library 🙌🏻

**Comment by MichaelDBA** [comment]
Cool!
