### ISSUE TITLE
pg_get_tabledef fails with camelCase table names

### ISSUE THREAD

**Issue by alaister** [MichaelDBA/pg_get_tabledef#17]
Hey Michael,
Me again, sorry 😅

When running `select * from public.pg_get_tabledef('public','myTable', false);` I get the following error:
```
Failed to run sql query: line=SQL statement "SELECT CASE WHEN pg_get_serial_sequence(v_qualified, v_colrec.column_name) IS NOT NULL THEN True ELSE False END" PL/pgSQL function pg_get_tabledef(character varying,character varying,boolean,tabledefs[]) line 230 at SQL statement. 42P01. relation "public.camelcase" does not exist
```

Thank you 🙏🏻

**Comment by MichaelDBA** [comment]
Is myTable a case sensitive table?

**Comment by alaister** [comment]
Yep, it would be something like `create table "myTable" (...`

**Comment by MichaelDBA** [comment]
Validated the bug,  thanks for the report.  Please test with the latest code.

**Comment by alaister** [comment]
Thanks, @MichaelDBA! Working great!

**Comment by MichaelDBA** [comment]
Introduced a bug with the fix

**Comment by MichaelDBA** [comment]
@alaister Fixed it again.

**Comment by MichaelDBA** [comment]
It was double quote enclosing non-case-senstive tables as well. Fixed it.

Please close again when you test it out.

**Comment by esabol** [comment]
It might be time for a GitHub Actions CI workflow? You could get some ideas from these:

https://github.com/segasai/q3c/blob/master/.github/workflows/test.yml
https://github.com/postgrespro/pgsphere/blob/master/.travis.yml (Travis CI, not GitHub Actions, but you can adapt it)

**Comment by alaister** [comment]
Thanks for the update, Michael! Updated on our side, and it's working well.
