### ISSUE TITLE
NOT NULL is being appended twice

### ISSUE THREAD

**Issue by alaister** [MichaelDBA/pg_get_tabledef#28]
Hi Michael,

I'm seeing `NOT NULL` being appended twice for `GENERATED ALWAYS AS IDENTITY` and `GENERATED BY DEFAULT AS IDENTITY` columns.

I think this is due to the code [here](https://github.com/MichaelDBA/pg_get_tabledef/blob/d3df600e806e4767aec9cc2640bf15258362b233/pg_get_tabledef.sql#L421) and [here](https://github.com/MichaelDBA/pg_get_tabledef/blob/d3df600e806e4767aec9cc2640bf15258362b233/pg_get_tabledef.sql#L423), as `NOT NULL` is then appended again [here](https://github.com/MichaelDBA/pg_get_tabledef/blob/d3df600e806e4767aec9cc2640bf15258362b233/pg_get_tabledef.sql#L432-L438).

Thanks!

**Comment by MichaelDBA** [comment]
Fixed, Please retest.  Thanks for the report!
