### ISSUE TITLE
Incomplete postgis geometry types

### ISSUE THREAD

**Issue by samodadela** [MichaelDBA/pg_get_tabledef#30]
When using `pg-clone-schema` I noticed that the cloned geometry fields are missing the details about the postgis type. 

For example, the original:
```
alter table locations
    add geometry geometry(Point, 4326) not null;
```

The clone:
```
alter table locations
    add geometry geometry not null;
```

The details can be found in a postgis specific table:
```
SELECT 
    f_geometry_column AS column_name,
    type AS geometry_type,
    srid
FROM 
    geometry_columns
WHERE 
    f_table_name = 'locations'
    AND f_table_schema = 'my_schema'
```

![image](https://github.com/user-attachments/assets/1a901232-1ff8-413b-a04a-8f1d475c322e)

Would it be possible to copy the postgis specific details if the extension is detected?

**Comment by MichaelDBA** [comment]
May I have a working example of this to test with?

**Comment by samodadela** [comment]
@MichaelDBA To get a working example you need to install the postgis extension and add a column, like above:
```
alter table your_table
    add geometry geometry(Point, 4326) not null;
```

That's it. If you compare the DDLs after cloning you'll see that it looses the detail about the type (Point) and SRID (43260.

**Comment by MichaelDBA** [comment]
Thanks, I have validated the bug and think I have fixed it with the latest code. Please validate.
@samodadela

**Comment by samodadela** [comment]
Thanks @MichaelDBA 

I tested it using the latest pg-clone-schema. There are no more differences regarding the postgis types using 'NODATA'.

**Comment by MichaelDBA** [comment]
I closing this one, but I still need to fix clone_schema for case where 'DATA', still broken there...
