### ISSUE TITLE
Inheritance table schema acquisition error

### ISSUE THREAD

**Issue by Hanko2024** [MichaelDBA/pg_get_tabledef#8]
1> test case：
CREATE SCHEMA a;
create table a.test_parent_23210642 ( i serial );
CREATE SCHEMA b;
create table b.test_child_23210642 () inherits (a.test_parent_23210642);

2> pg_get_tabledef show result:
select * from public.pg_get_tabledef('b','test_child_23210642', false);
pg_get_tabledef

CREATE TABLE b.test_child_23210642( +
) INHERITS (b.test_parent_23210642) +
TABLESPACE pg_default; +
+

The actual parent table test_parent_23210642 is under a schema

**Comment by Hanko2024** [comment]
dts1=> select version();
                                                 version                                                  
----------------------------------------------------------------------------------------------------------
 PostgreSQL 11.12 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit
(1 row)

dts1=>

**Comment by Hanko2024** [comment]
test case1：

CREATE SCHEMA a;
create table a.test_parent_23210642 ( i serial );

CREATE SCHEMA b;
create table b.test_child_23210642 () inherits (a.test_parent_23210642);
create view b.test_parent_view_23210642 as select * from a.test_parent_23210642;

**Comment by Hanko2024** [comment]
add test case2：

create table a.test_parent_a (i serial primary key);
create view a.test_parent_view_a as select * from a.test_parent_a;
create view a.test_view_a1 as select * from a.test_parent_view_a;

create table b.test_child_b (id integer references a.test_parent_a(i) primary key) inherits (a.test_parent_a);
create view b.test_child_view_b1 as select * from b.test_child_b;


pg_get_tabledef query a.test_parent_a and b.test_child_b

**Comment by Hanko2024** [comment]
add test case3

CREATE TABLE orders (
    id serial,
    user_name varchar(255),
    user_id  varchar(255),
    age  int not null
) PARTITION BY RANGE(age);

create table orders_r1 partition of orders for values from (MINVALUE) to (10000);  
create table orders_r2 partition of orders for values from (10000) to (200000);  
create table orders_r3 partition of orders for values from (200000) to (500000);  
create table orders_r4 partition of orders for values from (500000) to (MAXVALUE);

**Comment by MichaelDBA** [comment]
I never planned to make this script complex for relationships across other schemas. At least for the present time, I will make note of this exception in the Limitations Section in the README.

Nevertheless, I will still have a look at it when I get a chance to see if it wouldn't be too cumbersome to do it.  Perhaps, you might want to take a crack at it?

**Comment by esabol** [comment]
"Test case 3" above doesn't involve schemas. Maybe should be a separate issue?

**Comment by MichaelDBA** [comment]
No, I will deal with test case 3 here in this issue.

**Comment by Hanko2024** [comment]
across other schemas this feature is much needed，I would very much like to use this script if you can figure it out

**Comment by MichaelDBA** [comment]
Think I fixed test case 3: returns serial instead of a sequence reference.

Let me know if this fixes what you expected for test case 3.  For the multiple schema references, I am creating another issue for that referencing this issue.

**Comment by MichaelDBA** [comment]
@liuhangyu ???

**Comment by MichaelDBA** [comment]
Fixed.
